# LambdaTest AI Cloud Configuration
project_id: "01KCMNAXVGT7AHM2MA1TZCHCXD"
folder_id: "01KCMNAY3Z1022F9JXH82Z9117"
assignee: 3007853
environment_id: 186785
test_url: "https://staging-kaneai-nodejs-demo.onrender.com"
